### ISSUE TITLE
能支援將特定目錄下以及子目錄的圖片傳入 controlnet 嗎?

### ISSUE THREAD

**Issue by bluelovers** [pk5ls20/sd-webui-controlnet-fastload#2]
能支援將特定目錄下以及子目錄的圖片類似圖庫瀏覽器一樣展示
然後可以選擇傳入 controlnet 嗎?

**Comment by pk5ls20** [comment]
这样做的好处是可以**预览**要传入Controlnet的图片吗😂

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: bluelovers ***@***.***>
Sent: Sunday, August 13, 2023 12:00:09 PM
To: pk5ls20/sd-webui-controlnet-fastload ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [pk5ls20/sd-webui-controlnet-fastload] 能支援將特定目錄下以及子目錄的圖片傳入 controlnet 嗎? (Issue #2)


能支援將特定目錄下以及子目錄的圖片類似圖庫瀏覽器一樣展示
然後可以選擇傳入 controlnet 嗎?

**Comment by bluelovers** [comment]
恩 雖然網路上都能下載 controlnet 圖 
---
但目前 webui 內除了 圖庫瀏覽器 能做到瀏覽並且將圖傳入以外 就沒有了
可是他並不是設計用來支援 controlnet 
所以也不能依照 depth openpose 之類 來選擇要瀏覽的類別
---
另外如果不是透過本機來使用webui的話 也不能共享

**Comment by pk5ls20** [comment]
> 恩 雖然網路上都能下載 controlnet 圖
> 
> 但目前 webui 內除了 圖庫瀏覽器 能做到瀏覽並且將圖傳入以外 就沒有了 可是他並不是設計用來支援 controlnet 所以也不能依照 depth openpose 之類 來選擇要瀏覽的類別
> 
> 另外如果不是透過本機來使用webui的話 也不能共享

目前可以根据**生成图片中**PNGINFO来分类它们ControlNet使用的预处理器，当使用本插件生成的图片很多时，也许会很有帮助
