### ISSUE TITLE
Parameters not loading into controlnet

### ISSUE THREAD

**Issue by JS1989git** [pk5ls20/sd-webui-controlnet-fastload#6]
Hello. Please forgive me if this is in the wrong place or even the wrong question, but I don't think I am totally sure what this extension is doing. 

You say that it loads controlnet parameters that are saved into an image into controlnet, but I cannot seem to make this happen.

In the main tab "ControlNet Fastload v1.2," I upload an image with load only or load and save and it doesn't display anything. It just shows the file uploaded, but it doesn't show parameters or even the image (like in your example picture 2).

But I am not sure if that has anything to do with it either because in your example video when you send it to controlnet, all it loads in is just the image sent and enables the controlnet tab.  No data is carried over like weight, start step, controlnet model, etc.

Is this extension supposed to carry that data over into controlnet? Because if it is, it isn't for me.

Is there anything that does do that? Because that is really what I need to find: Something that carries over the controlnet data stored in the file metadata to the actual controlnet tabs. I thought that's what this was.

**Comment by pk5ls20** [comment]
I apologize for not detailing the usage process in the readme. I'll make sure to include a clearer guide in the upcoming [v1.2.1 update.](https://github.com/pk5ls20/sd-webui-controlnet-fastload/milestone/2)
The intended design of my extension is as follows:
Firstly, you need to **run both the Controlnet and Controlnet Fastload plugins simultaneously** and **set Controlnet Fastload to "Save Only."** At this point, the Controlnet Fastload extension will save the Controlnet data either in the generated image or in an additional .cni file, depending on your settings (by default, it's stored in the additional .cni file).
After that, you can drag and drop the image or .cni file containing the Controlnet data to "Load data from file" or view the saved data using the "View saved data" option.
I deeply apologize for any confusion or inconvenience caused. Please note that I'm an individual developer and appreciate your understanding and feedback.

**Comment by JS1989git** [comment]
That's alright. Thanks for taking the time to respond and uploading another video that I'm sure others will also find useful.

And just to let you know, I did figure out how to get controlnet metadata to import properly: It seems that it works correctly in SD.next/vlad diffusion, but is just broken in a1111.

**Comment by KINGLIFER** [comment]
Cool! Is this working in A1111 now?

**Comment by pk5ls20** [comment]
> Cool! Is this working in A1111 now?

Sure

**Comment by pk5ls20** [comment]
> Cool! Is this working in A1111 now?

Sure, this plugin is tested well in the latest master branch of a1111 now (https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/5ef669de080814067961f28357256e8fe27544f4), I am not closing this issue simply because it contains a basic plugin usage demo video, and I don’t have time to organize it into the documentation.

**Comment by KINGLIFER** [comment]
Sadly Error:  "C:\Users\AppData\Local\Temp\gradio\49fe93436c31582a03552cc27ef0f62b362585f1\00023-1054344531.png does not contain valid Controlnet Fastload data." And I hit save. Well was a good idea.

**Comment by pk5ls20** [comment]
> Sadly Error: "C:\Users\AppData\Local\Temp\gradio\49fe93436c31582a03552cc27ef0f62b362585f1\00023-1054344531.png does not contain valid Controlnet Fastload data." And I hit save. Well was a good idea.

Huh? Are you sure you followed the steps in the video **one by one**🤔?
